import Foundation

// MARK: - String Table

/// Static dictionaries for all user-facing strings.
/// Keys use dot-notation:  section.subsection.item
struct Strings {

    // ── English ──────────────────────────────────────────────────────────────
    static let en: [String: String] = [

        // Tabs
        "tab.home":      "Home",
        "tab.memories":  "Memories",
        "tab.family":    "Family",
        "tab.music":     "Music",
        "tab.settings":  "Settings",

        // Common actions
        "common.cancel":   "Cancel",
        "common.save":     "Save",
        "common.continue": "Continue",
        "common.skip":     "Skip",
        "common.ok":       "OK",
        "common.add":      "Add",
        "common.done":     "Done",
        "common.delete":   "Delete",
        "common.detect":   "Detect",
        "common.connect":  "Connect",

        // Home
        "home.greeting":                 "Welcome Back,",
        "home.friend":                   "Friend",
        "home.location.label":           "Your Location",
        "home.location.finding":         "Finding location…",
        "home.location.unavailable":     "Location unavailable",
        "home.mic.arc.top":              "REMEMBER WHO YOU ARE",
        "home.mic.arc.bottom":           "PRESS TO SPEAK",
        "home.mic.accessibility":        "Start listening",
        "home.mic.accessibility.hint":   "Double-tap to begin a voice conversation about your memories",
        "home.profile.accessibility":    "Your profile photo — tap to edit",
        "home.family.header":            "Your Family",
        "home.intro.title":              "What is Welcome Back?",
        "home.intro.body":               "A compassionate AI companion that helps you remember the people, places, and moments that matter most. Tap the microphone and start talking.",

        // Onboarding — Language picker
        "onboarding.language.title":    "Choose your language",
        "onboarding.language.subtitle": "You can change this later in Settings.",
        "onboarding.language.continue": "Continue",

        // Onboarding — Welcome
        "onboarding.welcome.title":    "Welcome Back",
        "onboarding.welcome.subtitle": "A compassionate companion\nfor your most precious memories.",
        "onboarding.welcome.cta":      "Get Started",
        "onboarding.welcome.time":     "Set up takes about 1 minute",
        "onboarding.welcome.a11y":     "Get started with Welcome Back",

        // Onboarding — Profile
        "onboarding.profile.title":              "What's your name?",
        "onboarding.profile.subtitle":           "We need your permission to use your information to support your memories. Your data always stays on your phone and is never shared anywhere else.",
        "onboarding.profile.name.label":         "Your Name",
        "onboarding.profile.name.placeholder":   "e.g. Harri",
        "onboarding.profile.photo.a11y":         "Add profile photo (optional)",
        "onboarding.profile.continue":           "Continue",
        "onboarding.profile.continue.a11y":      "Continue to next step",
        "onboarding.profile.continue.hint":      "Enter your name first",

        // Onboarding — Photo
        "onboarding.photo.title":    "Add Your Photo",
        "onboarding.photo.subtitle": "A photo helps make the app feel personal and familiar.",
        "onboarding.photo.tap":      "Tap to choose a photo",
        "onboarding.photo.continue": "Continue",
        "onboarding.photo.skip":     "Skip for now",

        // Onboarding — Add Family Member
        "onboarding.family.title":              "Add a Family Member",
        "onboarding.family.subtitle":           "Who is someone close to you? Start by adding one person — you can add more later.",
        "onboarding.family.name.label":         "Name",
        "onboarding.family.name.placeholder":   "e.g. Anna, Matti",
        "onboarding.family.rel.label":          "Relationship",
        "onboarding.family.rel.placeholder":    "e.g. Wife, Son, Daughter",
        "onboarding.family.memory.label":       "A Memory Together",
        "onboarding.family.memory.placeholder": "Write a few words about a special moment together, then tap Generate…",
        "onboarding.family.ai.button":          "Generate with AI ✦",
        "onboarding.family.ai.generating":      "Generating…",
        "onboarding.family.ai.hint":            "Write a brief description and AI will expand it into a warm memory",
        "onboarding.family.continue":           "Save & Continue",
        "onboarding.family.skip":               "Add later",

        // Onboarding — Family Tip
        "onboarding.family.tip.title":    "You Can Always Add More",
        "onboarding.family.tip.body":     "Add more family members and memories anytime from Settings → Family Members.",
        "onboarding.family.tip.continue": "Got it",

        // Onboarding — Add Place
        "onboarding.place.title":              "Add an Important Place",
        "onboarding.place.subtitle":           "A home, a cottage, or somewhere that holds special meaning for you.",
        "onboarding.place.name.label":         "Place Name",
        "onboarding.place.name.placeholder":   "e.g. Summer Cottage, Childhood Home",
        "onboarding.place.desc.label":         "What Makes It Special",
        "onboarding.place.desc.placeholder":   "Describe this place briefly, then tap Write with AI…",
        "onboarding.place.ai.button":          "Write with AI ✦",
        "onboarding.place.ai.generating":      "Writing…",
        "onboarding.place.continue":           "Save & Continue",
        "onboarding.place.skip":               "Skip for now",

        // Onboarding — Place Tip
        "onboarding.place.tip.title":    "More Places Later",
        "onboarding.place.tip.body":     "Add more important places anytime from Settings → Places.",
        "onboarding.place.tip.continue": "Got it",

        // Onboarding — Add Story
        "onboarding.story.title":              "Share a Memory",
        "onboarding.story.subtitle":           "Tell the app about a moment in your life you want to hold on to.",
        "onboarding.story.title.label":        "Title",
        "onboarding.story.title.placeholder":  "e.g. Our Wedding Day, Summer 1985",
        "onboarding.story.text.label":         "Your Story",
        "onboarding.story.text.placeholder":   "Write a few words or a brief description — AI can write the full story for you…",
        "onboarding.story.ai.button":          "Let AI Write It ✦",
        "onboarding.story.ai.generating":      "Writing your story…",
        "onboarding.story.continue":           "Save & Continue",
        "onboarding.story.skip":               "Skip for now",

        // Onboarding — Story Tip
        "onboarding.story.tip.title":    "Keep Building Your Memories",
        "onboarding.story.tip.body":     "Add more memories and stories anytime from Settings → Memories & Stories.",
        "onboarding.story.tip.continue": "Got it",

        // Onboarding — Music
        "onboarding.music.title":    "Your Music Memories",
        "onboarding.music.subtitle": "Music can unlock powerful memories. Connect Apple Music to play your favourite songs from throughout your life.",
        "onboarding.music.connect":  "Connect Apple Music",
        "onboarding.music.skip":     "Skip for now",
        "onboarding.music.note":     "You can connect Apple Music later in the Music tab.",

        // AI generation
        "onboarding.ai.error": "Couldn't generate — try again or write it yourself.",

        // Onboarding — Permissions
        "onboarding.permissions.title":           "A few permissions",
        "onboarding.permissions.subtitle":        "Welcome Back needs access to your\nmicrophone and photos.",
        "onboarding.permissions.mic.title":       "Microphone",
        "onboarding.permissions.mic.desc":        "Listen to your voice so the AI companion can understand you.",
        "onboarding.permissions.photos.title":    "Photo Library",
        "onboarding.permissions.photos.desc":     "Show your memory photos in the Memories tab.",
        "onboarding.permissions.allow":           "Allow Access",
        "onboarding.permissions.requesting":      "Requesting…",
        "onboarding.permissions.skip":            "Skip for now",
        "onboarding.permissions.skip.a11y":      "Skip permissions and continue",
        "onboarding.permissions.skip.hint":      "You can grant access later in iOS Settings",
        "onboarding.permissions.allow.a11y":     "Allow microphone and photo library access",
        "onboarding.permissions.denied.title":   "Permission Denied",
        "onboarding.permissions.denied.open":    "Open Settings",
        "onboarding.permissions.denied.skip":    "Skip",
        "onboarding.permissions.denied.message": "Microphone or photo access was previously denied. Open Settings to allow access, or skip to continue without these features.",

        // Onboarding — Model Download
        "onboarding.model.title":              "Download the AI",
        "onboarding.model.subtitle":           "Welcome Back uses an on-device AI.\nYour conversations are completely private\nand work without internet.",
        "onboarding.model.card.subtitle":      "Google on-device AI · %@ · Wi-Fi recommended",
        "onboarding.model.ready":              "AI Ready!",
        "onboarding.model.downloading":        "Downloading Gemma 4…",
        "onboarding.model.download.button":    "Download Now · %@",
        "onboarding.model.download.later":     "Download later",
        "onboarding.model.cancel":             "Cancel Download",
        "onboarding.model.cancel.confirm.title":   "Cancel Download?",
        "onboarding.model.cancel.confirm.message": "The download will need to start from the beginning if cancelled.",
        "onboarding.model.cancel.confirm.action":  "Cancel Download",
        "onboarding.model.cancel.continue":        "Continue Downloading",
        "onboarding.model.storage.title":      "Not Enough Storage",
        "onboarding.model.storage.message":    "Your device needs at least 2.8 GB of free space to download the AI model. Free up some storage and try again, or download later from Settings.",
        "onboarding.model.storage.later":      "Download Later",
        "onboarding.model.download.a11y":      "Download Gemma 4 AI model, %@",
        "onboarding.model.later.a11y":         "Skip model download and continue",
        "onboarding.model.later.hint":         "You can download the AI model later from Settings",

        // Onboarding — Complete
        "onboarding.complete.title":    "You're all set%@!",
        "onboarding.complete.subtitle": "Welcome Back is ready to help you\nrediscover your memories.",
        "onboarding.complete.cta":      "Start Remembering",
        "onboarding.complete.cta.a11y": "Start using Welcome Back",
        "onboarding.complete.tip1":     "Tap the big mic button on the Home screen to start a conversation.",
        "onboarding.complete.tip2":     "Add family members in Settings so the app can introduce them.",
        "onboarding.complete.tip3":     "Your Memories tab shows photos from your photo library grouped by month.",

        // Settings
        "settings.title":                    "Settings",
        "settings.section.general":          "General",
        "settings.section.ai":               "Artificial Intelligence",
        "settings.section.system":           "System",
        "settings.section.legal":            "Legal",
        "settings.section.reset":            "Reset",
        "settings.personal.title":           "Personal Info",
        "settings.personal.subtitle":        "Name, address, biography",
        "settings.family.title":             "Family Members",
        "settings.places.title":             "Places",
        "settings.memories.title":           "Memories & Stories",
        "settings.notifications.title":      "Notifications",
        "settings.notifications.enabled":    "Enabled",
        "settings.notifications.disabled":   "Disabled",
        "settings.language.title":           "Language",
        "settings.ai.model.title":           "Voice AI Model",
        "settings.ai.model.ready":           "Ready",
        "settings.ai.model.not_downloaded":  "Not Downloaded",
        "settings.ai.voice_mode.title":      "Voice Mode",
        "settings.ai.voice_mode.local":      "Local (On-Device)",
        "settings.ai.companion.title":       "Companion Voice",
        "settings.ai.companion.personal":    "iOS Personal Voice",
        "settings.ai.companion.default":     "Default system voice",
        "settings.system.about.title":       "About",
        "settings.system.about.subtitle":    "Version 1.3",
        "settings.system.licenses.title":    "Open Source Licenses",
        "settings.system.licenses.subtitle": "llama.cpp (MIT)",
        "settings.legal.privacy.title":      "Privacy Policy",
        "settings.legal.privacy.subtitle":   "How your data is handled",
        "settings.legal.terms.title":        "Terms of Service",
        "settings.legal.terms.subtitle":     "Usage terms and disclaimers",
        "settings.reset.title":              "Reset to New User",
        "settings.reset.subtitle":           "Erase all data and restart onboarding",
        "settings.reset.confirm.title":      "Reset to New User?",
        "settings.reset.confirm.action":     "Reset Everything",
        "settings.reset.confirm.message":    "This will erase all profile data, family members, and saved photos. The onboarding flow will restart. This cannot be undone.",
        "settings.footer":                   "Welcome Back uses on-device AI to protect your privacy",
        "settings.privacy_link":             "Privacy Policy",

        // Personal Info
        "personalinfo.title":               "Personal Info",
        "personalinfo.photo.title":         "Your Photo",
        "personalinfo.photo.change":        "Change Photo",
        "personalinfo.photo.hint":          "Tap to choose from your photo library",
        "personalinfo.about.title":         "About You",
        "personalinfo.name":                "Name",
        "personalinfo.address":             "Address",
        "personalinfo.biography":           "Biography",
        "personalinfo.biography.placeholder": "A few words about yourself…",
        "personalinfo.family.title":        "Family Members",

        // Family
        "family.title":                 "Family",
        "family.empty":                 "No family members yet",
        "family.empty.hint":            "Add family members in Settings",
        "family.management.title":      "Family Members",
        "family.add":                   "Add member",
        "family.empty.management.hint": "Tap \"Add member\" to get started",
        "family.detail.add.title":      "Add Family Member",
        "family.detail.photos.title":   "Photo Gallery",
        "family.detail.about.title":    "About",
        "family.detail.name.label":     "Name",
        "family.detail.name.placeholder":         "Full name",
        "family.detail.relationship.label":       "Relationship",
        "family.detail.relationship.placeholder": "e.g. Daughter, Son, Wife",
        "family.detail.phone.label":              "Phone",
        "family.detail.biography.label":          "Biography",
        "family.detail.biography.placeholder":    "A few words about this person…",
        "family.detail.memories.title":           "Shared Memories",
        "family.detail.memory1.label":            "Memory 1",
        "family.detail.memory1.placeholder":      "A special moment together…",
        "family.detail.memory2.label":            "Memory 2",
        "family.detail.memory2.placeholder":      "Another cherished memory…",
        "family.detail.add.photo":               "Add",
        "family.detail.choose.photo":            "Choose Profile Photo",

        // Memories
        "memories.title":          "Memories",
        "memories.people":         "People",
        "memories.people.empty":   "Add family members in Settings to see them here.",
        "memories.places":         "Places",
        "memories.places.empty":   "Add important places in Settings to see them here.",
        "memories.stories":        "Your Stories",
        "memories.stories.empty":  "Add memories and stories in Settings to see them here.",
        "memories.place.about":    "About This Place",
        "memories.place.no_desc":  "No description added yet. Edit in Settings › Places.",
        "memories.place.location": "Location",
        "memories.place.maps":     "Open in Maps",
        "memories.place.photo_loc": "Location read from photo",
        "memories.place.no_loc":   "No location set.\nAdd a photo with GPS data or set coordinates in Settings › Places.",

        // Memories Management
        "memories.management.title":      "Memories & Stories",
        "memories.management.add":        "Add memory",
        "memories.management.empty":      "No memories yet",
        "memories.management.empty.hint": "Tap \"Add memory\" to save important stories and moments",
        "memories.detail.add.title":      "Add Memory",
        "memories.detail.title.label":    "Title",
        "memories.detail.title.placeholder": "e.g. Our Wedding Day",
        "memories.detail.date.label":     "Date",
        "memories.detail.date.placeholder": "e.g. June 14, 1980",
        "memories.detail.photo":          "Choose Photo",
        "memories.detail.category.label":  "Category",
        "memories.detail.story.label":     "Story",
        "memories.detail.story.placeholder": "Tell the story of this memory…",
        "memories.detail.delete":          "Delete Memory",

        // Places Management
        "places.title":                "Places",
        "places.add":                  "Add place",
        "places.empty":                "No places yet",
        "places.empty.hint":           "Tap \"Add place\" to save important locations",
        "places.detail.add.title":     "Add Place",
        "places.detail.name.label":    "Name",
        "places.detail.name.placeholder": "e.g. Summer Cottage, Childhood Home",
        "places.detail.desc.label":    "Description",
        "places.detail.desc.placeholder": "Describe this place and why it matters…",
        "places.detail.coords.title":  "Coordinates",
        "places.detail.lat.label":     "Latitude",
        "places.detail.lat.placeholder": "e.g. 61.50",
        "places.detail.lon.label":     "Longitude",
        "places.detail.lon.placeholder": "e.g. 28.10",
        "places.detail.photo":           "Choose Photo",
        "places.detail.preview":         "Preview",
        "places.detail.delete":          "Delete Place",

        // Legal
        "legal.open_safari":             "Open in Safari",

        // Playback
        "playback.preparing":    "Preparing a message…",
        "playback.loading":      "LOADING…",
        "playback.now_playing":  "NOW PLAYING",
        "playback.tap_listen":   "TAP TO LISTEN",

        // Listening
        "listening.end":          "End",
        "listening.end.a11y":     "End conversation",
        "listening.end.hint":     "Stops the AI conversation and closes this screen",
        "listening.connecting":   "Connecting...",
        "listening.loading":      "Loading Gemma 4…",
        "listening.ready":        "I'm listening. Take your time…",
        "listening.go_on":        "Go on, I'm listening…",
        "listening.moment":       "Just a moment…",
        "listening.response":     "Listening to response…",
        "listening.done":         "I'm listening…",
        "listening.ended":        "Session ended.",
        "listening.a11y.listen":  "Listening. Take your time.",
        "listening.a11y.speak":   "AI is speaking.",
        "listening.a11y.think":   "Thinking.",
        "listening.header":       "Listening...",
        "listening.header.loading": "Loading…",

        // Music
        "music.title":         "Memory Lane",
        "music.now_playing":   "Now playing",
        "music.no_songs":      "No songs found in your library.\nAdd music to Apple Music and come back.",
        "music.connect.title": "Connect Apple Music",
        "music.connect.desc":  "Allow access to play your favourite songs from your Apple Music library.",
        "music.connect.btn":   "Connect",
        "music.denied":        "Apple Music access was denied.\nPlease enable it in Settings › Privacy › Media & Apple Music.",
        "music.loading":       "Loading your music…",
        "music.mixes":         "Memory Mixes",

        // Model Settings
        "modelsettings.title":          "Voice AI Model",
        "modelsettings.status":         "Status",
        "modelsettings.ready":          "Gemma 4 Ready",
        "modelsettings.not_downloaded": "Model Not Downloaded",
        "modelsettings.model.desc":     "Google Gemma 4 E2B — best on-device AI",
        "modelsettings.download":       "Download",
        "modelsettings.downloading":    "Downloading Gemma 4 E2B…",
        "modelsettings.download.cancel": "Cancel Download",
        "modelsettings.download.button": "Download Gemma 4 E2B",
        "modelsettings.download.done":   "Gemma 4 downloaded and ready",
        "modelsettings.download.desc":   "Gemma 4 E2B is Google's best on-device AI model (~2.3 GB). A Wi-Fi connection is recommended.",
        "modelsettings.storage":         "Storage",
        "modelsettings.storage.available": "Available Storage",
        "modelsettings.storage.delete":  "Delete",
        "modelsettings.storage.on_disk": "%.1f GB on disk",

        // Voice Selection
        "voiceselection.title":             "AI Voice",
        "voiceselection.section.companion": "AI Companion Voice",
        "voiceselection.default":           "Default Voice",
        "voiceselection.default.subtitle":  "Apple TTS (English)",
        "voiceselection.personal.section":  "iOS Personal Voice",
        "voiceselection.personal.empty":    "No Personal Voices found. Create one in iOS Settings → Accessibility → Personal Voice.",
        "voiceselection.personal.enable":   "Enable iOS Personal Voice",
        "voiceselection.personal.subtitle": "Apple's accessibility voice (set up in iPhone Settings)",
        "voiceselection.footer":            "iOS Personal Voice is Apple's own accessibility feature — not related to voice cloning. Set it up in iPhone Settings → Accessibility → Personal Voice (takes ~15 min).",
        "voiceselection.personal.label":    "Personal Voice",
        "voiceselection.personal.denied":   "Personal Voice access denied. Enable in iOS Settings → Privacy → Personal Voice.",
        "voiceselection.personal.unsupported": "Personal Voice is not supported on this device.",

        // Voice Mode Settings
        "voicemode.active":                 "Active Mode",
        "voicemode.offline_desc":           "Runs entirely offline · No data leaves your phone",
        "voicemode.model.ready":            "Gemma 4 Model Ready",
        "voicemode.model.ready.desc":       "2.3 GB · Downloaded",
        "voicemode.model.not_downloaded":   "Gemma 4 Model Not Downloaded",
        "voicemode.model.download_hint":    "Tap to download · 2.3 GB required",
        "voicemode.about":                  "About",
        "voicemode.privacy.title":          "Your Privacy",
        "voicemode.privacy.text":           "All conversations run entirely on your iPhone. No audio, no text, and no personal data is ever sent to external servers.",
        "voicemode.offline.title":          "Works Offline",
        "voicemode.offline.text":           "Once the Gemma 4 model is downloaded, Welcome Back works without any internet connection.",

        // Notifications
        "notifications.title":               "Notifications",
        "notifications.status":              "Status",
        "notifications.enable":              "Enable Notifications",
        "notifications.checkin":             "Daily check-in reminders",
        "notifications.remind_at":           "Remind Me At",
        "notifications.topics.title":        "What to Talk About",
        "notifications.topics.header":       "Topics & Reminders",
        "notifications.topics.placeholder":  "Describe what the daily check-in should focus on — e.g. medication, appointments, memories.",

        // Language Settings
        "languagesettings.title":    "Language",
        "languagesettings.subtitle": "Choose the language used throughout the app.",
    ]

    // ── Finnish ──────────────────────────────────────────────────────────────
    static let fi: [String: String] = [

        // Välilehdet
        "tab.home":      "Koti",
        "tab.memories":  "Muistot",
        "tab.family":    "Perhe",
        "tab.music":     "Musiikki",
        "tab.settings":  "Asetukset",

        // Yleiset toiminnot
        "common.cancel":   "Peruuta",
        "common.save":     "Tallenna",
        "common.continue": "Jatka",
        "common.skip":     "Ohita",
        "common.ok":       "OK",
        "common.add":      "Lisää",
        "common.done":     "Valmis",
        "common.delete":   "Poista",
        "common.detect":   "Hae",
        "common.connect":  "Yhdistä",

        // Koti
        "home.greeting":                 "Hei taas,",
        "home.friend":                   "Ystävä",
        "home.location.label":           "Sijaintisi",
        "home.location.finding":         "Haetaan sijaintia…",
        "home.location.unavailable":     "Sijainti ei saatavilla",
        "home.mic.arc.top":              "MUISTA KUKA OLET",
        "home.mic.arc.bottom":           "PAINA JA PUHU",
        "home.mic.accessibility":        "Aloita kuuntelu",
        "home.mic.accessibility.hint":   "Kaksoisnapauta aloittaaksesi äänijuttelun muistoistasi",
        "home.profile.accessibility":    "Profiilikuvasi — napauta muokataksesi",
        "home.family.header":            "Perheesi",
        "home.intro.title":              "Mikä on Welcome Back?",
        "home.intro.body":               "Välittävä tekoälykumppani, joka auttaa sinua muistamaan tärkeimmät ihmiset, paikat ja hetket. Napauta mikrofonia ja ala puhua.",

        // Onboarding — Kielivalinta
        "onboarding.language.title":    "Valitse kieli",
        "onboarding.language.subtitle": "Voit muuttaa tätä myöhemmin asetuksissa.",
        "onboarding.language.continue": "Jatka",

        // Onboarding — Tervetuloa
        "onboarding.welcome.title":    "Welcome Back",
        "onboarding.welcome.subtitle": "Välittävä kumppani\nkalleimmille muistoillesi.",
        "onboarding.welcome.cta":      "Aloita",
        "onboarding.welcome.time":     "Käyttöönotto kestää noin minuutin",
        "onboarding.welcome.a11y":     "Aloita Welcome Back -sovelluksen käyttö",

        // Onboarding — Profiili
        "onboarding.profile.title":              "Mikä sinun nimesi on?",
        "onboarding.profile.subtitle":           "Tarvitsemme luvan tietojesi käyttöön, jotta voimme tukea muisteluasi. Tiedot pysyvät aina puhelimellasi. Niitä ei jaeta mihinkään muualle.",
        "onboarding.profile.name.label":         "Nimesi",
        "onboarding.profile.name.placeholder":   "esim. Harri",
        "onboarding.profile.photo.a11y":         "Lisää profiilikuva (valinnainen)",
        "onboarding.profile.continue":           "Jatka",
        "onboarding.profile.continue.a11y":      "Jatka seuraavaan vaiheeseen",
        "onboarding.profile.continue.hint":      "Kirjoita ensin nimesi",

        // Onboarding — Kuva
        "onboarding.photo.title":    "Lisää oma kuvasi",
        "onboarding.photo.subtitle": "Kuva tekee sovelluksesta henkilökohtaisemman ja tutumman.",
        "onboarding.photo.tap":      "Napauta valitaksesi kuvan",
        "onboarding.photo.continue": "Jatka",
        "onboarding.photo.skip":     "Ohita toistaiseksi",

        // Onboarding — Lisää perheenjäsen
        "onboarding.family.title":              "Lisää perheenjäsen",
        "onboarding.family.subtitle":           "Kuka sinulle läheinen ihminen on? Lisää yksi henkilö nyt — voit lisätä lisää myöhemmin.",
        "onboarding.family.name.label":         "Nimi",
        "onboarding.family.name.placeholder":   "esim. Anna, Matti",
        "onboarding.family.rel.label":          "Suhde",
        "onboarding.family.rel.placeholder":    "esim. Vaimo, Poika, Tytär",
        "onboarding.family.memory.label":       "Yhteinen muisto",
        "onboarding.family.memory.placeholder": "Kirjoita muutama sana erityisestä hetkestä yhdessä, sitten napauta Generoi…",
        "onboarding.family.ai.button":          "Generoi tekoälyllä ✦",
        "onboarding.family.ai.generating":      "Generoidaan…",
        "onboarding.family.ai.hint":            "Kirjoita lyhyt kuvaus ja tekoäly laajentaa sen lämpimäksi muistoksi",
        "onboarding.family.continue":           "Tallenna ja jatka",
        "onboarding.family.skip":               "Lisää myöhemmin",

        // Onboarding — Perheenvinkki
        "onboarding.family.tip.title":    "Voit lisätä lisää myöhemmin",
        "onboarding.family.tip.body":     "Lisää perheenjäseniä ja muistoja milloin tahansa kohdasta Asetukset → Perheenjäsenet.",
        "onboarding.family.tip.continue": "Selvä",

        // Onboarding — Lisää paikka
        "onboarding.place.title":              "Lisää tärkeä paikka",
        "onboarding.place.subtitle":           "Koti, mökki tai jokin paikka, jolla on erityinen merkitys sinulle.",
        "onboarding.place.name.label":         "Paikan nimi",
        "onboarding.place.name.placeholder":   "esim. Kesämökki, Lapsuudenkoti",
        "onboarding.place.desc.label":         "Miksi se on erityinen",
        "onboarding.place.desc.placeholder":   "Kuvaile paikkaa lyhyesti, sitten napauta Kirjoita tekoälyllä…",
        "onboarding.place.ai.button":          "Kirjoita tekoälyllä ✦",
        "onboarding.place.ai.generating":      "Kirjoitetaan…",
        "onboarding.place.continue":           "Tallenna ja jatka",
        "onboarding.place.skip":               "Ohita toistaiseksi",

        // Onboarding — Paikkavinkki
        "onboarding.place.tip.title":    "Lisää paikkoja myöhemmin",
        "onboarding.place.tip.body":     "Lisää tärkeitä paikkoja milloin tahansa kohdasta Asetukset → Paikat.",
        "onboarding.place.tip.continue": "Selvä",

        // Onboarding — Lisää tarina
        "onboarding.story.title":              "Jaa muisto",
        "onboarding.story.subtitle":           "Kerro sovellukselle hetkestä elämässäsi, jonka haluat muistaa.",
        "onboarding.story.title.label":        "Otsikko",
        "onboarding.story.title.placeholder":  "esim. Häämme, Kesä 1985",
        "onboarding.story.text.label":         "Muistosi",
        "onboarding.story.text.placeholder":   "Kirjoita muutama sana tai lyhyt kuvaus — tekoäly voi kirjoittaa täyden tarinan puolestasi…",
        "onboarding.story.ai.button":          "Anna tekoälyn kirjoittaa ✦",
        "onboarding.story.ai.generating":      "Kirjoitetaan tarinaasi…",
        "onboarding.story.continue":           "Tallenna ja jatka",
        "onboarding.story.skip":               "Ohita toistaiseksi",

        // Onboarding — Tarinavinkki
        "onboarding.story.tip.title":    "Jatka muistojen rakentamista",
        "onboarding.story.tip.body":     "Lisää muistoja ja tarinoita milloin tahansa kohdasta Asetukset → Muistot ja tarinat.",
        "onboarding.story.tip.continue": "Selvä",

        // Onboarding — Musiikki
        "onboarding.music.title":    "Musiikkimuistosi",
        "onboarding.music.subtitle": "Musiikki voi avata voimakkaita muistoja. Yhdistä Apple Music soittaaksesi suosikkikappaleitasi elämäsi varrelta.",
        "onboarding.music.connect":  "Yhdistä Apple Music",
        "onboarding.music.skip":     "Ohita toistaiseksi",
        "onboarding.music.note":     "Voit yhdistää Apple Musicin myöhemmin Musiikki-välilehdeltä.",

        // Tekoälyn generointi
        "onboarding.ai.error": "Generointi epäonnistui — yritä uudelleen tai kirjoita itse.",

        // Onboarding — Luvat
        "onboarding.permissions.title":           "Muutama lupa",
        "onboarding.permissions.subtitle":        "Welcome Back tarvitsee pääsyn\nmikrofonillesi ja kuvillesi.",
        "onboarding.permissions.mic.title":       "Mikrofoni",
        "onboarding.permissions.mic.desc":        "Kuuntelee ääntäsi, jotta tekoälykumppani voi ymmärtää sinua.",
        "onboarding.permissions.photos.title":    "Kuvagalleria",
        "onboarding.permissions.photos.desc":     "Näyttää muistokuvasi Muistot-välilehdellä.",
        "onboarding.permissions.allow":           "Salli pääsy",
        "onboarding.permissions.requesting":      "Pyydetään…",
        "onboarding.permissions.skip":            "Ohita toistaiseksi",
        "onboarding.permissions.skip.a11y":      "Ohita luvat ja jatka",
        "onboarding.permissions.skip.hint":      "Voit myöntää pääsyn myöhemmin iOS-asetuksissa",
        "onboarding.permissions.allow.a11y":     "Salli mikrofoni- ja kuvagalleriapääsy",
        "onboarding.permissions.denied.title":   "Lupa evätty",
        "onboarding.permissions.denied.open":    "Avaa asetukset",
        "onboarding.permissions.denied.skip":    "Ohita",
        "onboarding.permissions.denied.message": "Mikrofoni- tai kuvaoikeus on aiemmin evätty. Avaa asetukset salliaksesi pääsy tai ohita jatkaaksesi ilman näitä ominaisuuksia.",

        // Onboarding — Mallin lataus
        "onboarding.model.title":              "Lataa tekoäly",
        "onboarding.model.subtitle":           "Welcome Back käyttää laitteessa toimivaa tekoälyä.\nKeskustelusi ovat täysin yksityisiä\nja toimivat ilman internetyhteyttä.",
        "onboarding.model.card.subtitle":      "Google laitteen tekoäly · %@ · Wi-Fi suositellaan",
        "onboarding.model.ready":              "Tekoäly valmis!",
        "onboarding.model.downloading":        "Ladataan Gemma 4…",
        "onboarding.model.download.button":    "Lataa nyt · %@",
        "onboarding.model.download.later":     "Lataa myöhemmin",
        "onboarding.model.cancel":             "Peruuta lataus",
        "onboarding.model.cancel.confirm.title":   "Peruutetaanko lataus?",
        "onboarding.model.cancel.confirm.message": "Lataus täytyy aloittaa alusta, jos se peruutetaan.",
        "onboarding.model.cancel.confirm.action":  "Peruuta lataus",
        "onboarding.model.cancel.continue":        "Jatka latausta",
        "onboarding.model.storage.title":      "Ei tarpeeksi tallennustilaa",
        "onboarding.model.storage.message":    "Laitteesi tarvitsee vähintään 2,8 Gt vapaata tilaa tekoälymallin lataamiseksi. Vapauta tallennustilaa ja yritä uudelleen tai lataa myöhemmin asetuksista.",
        "onboarding.model.storage.later":      "Lataa myöhemmin",
        "onboarding.model.download.a11y":      "Lataa Gemma 4 -tekoälymalli, %@",
        "onboarding.model.later.a11y":         "Ohita mallin lataus ja jatka",
        "onboarding.model.later.hint":         "Voit ladata tekoälymallin myöhemmin asetuksista",

        // Onboarding — Valmis
        "onboarding.complete.title":    "Kaikki on valmiina%@!",
        "onboarding.complete.subtitle": "Welcome Back on valmis auttamaan sinua\nmuistamaan muistosi.",
        "onboarding.complete.cta":      "Aloita muistelu",
        "onboarding.complete.cta.a11y": "Aloita Welcome Backin käyttö",
        "onboarding.complete.tip1":     "Napauta isoa mikrofoninappia kotinäytöllä aloittaaksesi keskustelun.",
        "onboarding.complete.tip2":     "Lisää perheenjäseniä asetuksissa, jotta sovellus voi esitellä heidät.",
        "onboarding.complete.tip3":     "Muistot-välilehti näyttää kuvat kuvakirjastostasi ryhmiteltyinä kuukauden mukaan.",

        // Asetukset
        "settings.title":                    "Asetukset",
        "settings.section.general":          "Yleiset",
        "settings.section.ai":               "Tekoäly",
        "settings.section.system":           "Järjestelmä",
        "settings.section.legal":            "Juridinen",
        "settings.section.reset":            "Nollaa",
        "settings.personal.title":           "Henkilötiedot",
        "settings.personal.subtitle":        "Nimi, osoite, elämäkerta",
        "settings.family.title":             "Perheenjäsenet",
        "settings.places.title":             "Paikat",
        "settings.memories.title":           "Muistot ja tarinat",
        "settings.notifications.title":      "Ilmoitukset",
        "settings.notifications.enabled":    "Käytössä",
        "settings.notifications.disabled":   "Pois käytöstä",
        "settings.language.title":           "Kieli",
        "settings.ai.model.title":           "Äänitekoälymalli",
        "settings.ai.model.ready":           "Valmis",
        "settings.ai.model.not_downloaded":  "Ei ladattu",
        "settings.ai.voice_mode.title":      "Äänitila",
        "settings.ai.voice_mode.local":      "Paikallinen (laitteessa)",
        "settings.ai.companion.title":       "Kumppanin ääni",
        "settings.ai.companion.personal":    "iOS Henkilökohtainen ääni",
        "settings.ai.companion.default":     "Oletusjärjestelmäääni",
        "settings.system.about.title":       "Tietoja",
        "settings.system.about.subtitle":    "Versio 1.0.0",
        "settings.system.licenses.title":    "Avoimen lähdekoodin lisenssit",
        "settings.system.licenses.subtitle": "llama.cpp (MIT)",
        "settings.legal.privacy.title":      "Tietosuojakäytäntö",
        "settings.legal.privacy.subtitle":   "Miten tietojasi käsitellään",
        "settings.legal.terms.title":        "Käyttöehdot",
        "settings.legal.terms.subtitle":     "Käyttöehdot ja vastuuvapauslausekkeet",
        "settings.reset.title":              "Nollaa uudeksi käyttäjäksi",
        "settings.reset.subtitle":           "Poista kaikki tiedot ja käynnistä käyttöönotto uudelleen",
        "settings.reset.confirm.title":      "Nollaatko uudeksi käyttäjäksi?",
        "settings.reset.confirm.action":     "Nollaa kaikki",
        "settings.reset.confirm.message":    "Tämä poistaa kaikki profiilitiedot, perheenjäsenet ja tallennetut kuvat. Käyttöönottoprosessi käynnistyy uudelleen. Tätä ei voi peruuttaa.",
        "settings.footer":                   "Welcome Back käyttää laitteen tekoälyä suojellakseen yksityisyyttäsi",
        "settings.privacy_link":             "Tietosuojakäytäntö",

        // Henkilötiedot
        "personalinfo.title":               "Henkilötiedot",
        "personalinfo.photo.title":         "Kuvasi",
        "personalinfo.photo.change":        "Vaihda kuva",
        "personalinfo.photo.hint":          "Napauta valitaksesi kuvakirjastostasi",
        "personalinfo.about.title":         "Tietoja sinusta",
        "personalinfo.name":                "Nimi",
        "personalinfo.address":             "Osoite",
        "personalinfo.biography":           "Elämäkerta",
        "personalinfo.biography.placeholder": "Muutama sana itsestäsi…",
        "personalinfo.family.title":        "Perheenjäsenet",

        // Perhe
        "family.title":                 "Perhe",
        "family.empty":                 "Ei perheenjäseniä vielä",
        "family.empty.hint":            "Lisää perheenjäseniä asetuksissa",
        "family.management.title":      "Perheenjäsenet",
        "family.add":                   "Lisää jäsen",
        "family.empty.management.hint": "Napauta \"Lisää jäsen\" aloittaaksesi",
        "family.detail.add.title":      "Lisää perheenjäsen",
        "family.detail.photos.title":   "Kuvagalleria",
        "family.detail.about.title":    "Tietoja",
        "family.detail.name.label":     "Nimi",
        "family.detail.name.placeholder":         "Koko nimi",
        "family.detail.relationship.label":       "Suhde",
        "family.detail.relationship.placeholder": "esim. Tytär, Poika, Vaimo",
        "family.detail.phone.label":              "Puhelin",
        "family.detail.biography.label":          "Elämäkerta",
        "family.detail.biography.placeholder":    "Muutama sana tästä henkilöstä…",
        "family.detail.memories.title":           "Yhteiset muistot",
        "family.detail.memory1.label":            "Muisto 1",
        "family.detail.memory1.placeholder":      "Erityinen hetki yhdessä…",
        "family.detail.memory2.label":            "Muisto 2",
        "family.detail.memory2.placeholder":      "Toinen rakas muisto…",
        "family.detail.add.photo":               "Lisää",
        "family.detail.choose.photo":            "Valitse profiilikuva",

        // Muistot
        "memories.title":          "Muistot",
        "memories.people":         "Ihmiset",
        "memories.people.empty":   "Lisää perheenjäseniä asetuksissa nähdäksesi heidät täällä.",
        "memories.places":         "Paikat",
        "memories.places.empty":   "Lisää tärkeitä paikkoja asetuksissa nähdäksesi ne täällä.",
        "memories.stories":        "Tarinasi",
        "memories.stories.empty":  "Lisää muistoja ja tarinoita asetuksissa nähdäksesi ne täällä.",
        "memories.place.about":    "Tästä paikasta",
        "memories.place.no_desc":  "Kuvausta ei ole lisätty. Muokkaa asetuksissa › Paikat.",
        "memories.place.location": "Sijainti",
        "memories.place.maps":     "Avaa kartassa",
        "memories.place.photo_loc": "Sijainti luettu kuvasta",
        "memories.place.no_loc":   "Sijaintia ei asetettu.\nLisää kuva GPS-tiedoilla tai aseta koordinaatit asetuksissa › Paikat.",

        // Muistojen hallinta
        "memories.management.title":      "Muistot ja tarinat",
        "memories.management.add":        "Lisää muisto",
        "memories.management.empty":      "Ei muistoja vielä",
        "memories.management.empty.hint": "Napauta \"Lisää muisto\" tallentaaksesi tarinoita ja hetkiä",
        "memories.detail.add.title":      "Lisää muisto",
        "memories.detail.title.label":    "Otsikko",
        "memories.detail.title.placeholder": "esim. Häämme päivä",
        "memories.detail.date.label":     "Päivämäärä",
        "memories.detail.date.placeholder": "esim. 14. kesäkuuta 1980",
        "memories.detail.photo":          "Valitse kuva",
        "memories.detail.category.label":  "Kategoria",
        "memories.detail.story.label":     "Tarina",
        "memories.detail.story.placeholder": "Kerro tämän muiston tarina…",
        "memories.detail.delete":          "Poista muisto",

        // Paikkojen hallinta
        "places.title":                "Paikat",
        "places.add":                  "Lisää paikka",
        "places.empty":                "Ei paikkoja vielä",
        "places.empty.hint":           "Napauta \"Lisää paikka\" tallentaaksesi tärkeitä paikkoja",
        "places.detail.add.title":     "Lisää paikka",
        "places.detail.name.label":    "Nimi",
        "places.detail.name.placeholder": "esim. Kesämökki, Lapsuudenkoti",
        "places.detail.desc.label":    "Kuvaus",
        "places.detail.desc.placeholder": "Kuvaile tämä paikka ja miksi se on tärkeä…",
        "places.detail.coords.title":  "Koordinaatit",
        "places.detail.lat.label":     "Leveysaste",
        "places.detail.lat.placeholder": "esim. 61.50",
        "places.detail.lon.label":     "Pituusaste",
        "places.detail.lon.placeholder": "esim. 28.10",
        "places.detail.photo":           "Valitse kuva",
        "places.detail.preview":         "Esikatselu",
        "places.detail.delete":          "Poista paikka",

        // Juridinen
        "legal.open_safari":             "Avaa Safarissa",

        // Toisto
        "playback.preparing":    "Valmistellaan viestiä…",
        "playback.loading":      "LADATAAN…",
        "playback.now_playing":  "NYT SOISEE",
        "playback.tap_listen":   "NAPAUTA KUUNNELLAKSESI",

        // Kuuntelu
        "listening.end":          "Lopeta",
        "listening.end.a11y":     "Lopeta keskustelu",
        "listening.end.hint":     "Lopettaa tekoälykeskustelun ja sulkee näytön",
        "listening.connecting":   "Yhdistetään...",
        "listening.loading":      "Ladataan Gemma 4…",
        "listening.ready":        "Kuuntelen. Ota aikasi…",
        "listening.go_on":        "Jatka, kuuntelen…",
        "listening.moment":       "Odota hetki…",
        "listening.response":     "Kuunnellaan vastausta…",
        "listening.done":         "Kuuntelen…",
        "listening.ended":        "Istunto päättyi.",
        "listening.a11y.listen":  "Kuunnellaan. Ota aikasi.",
        "listening.a11y.speak":   "Tekoäly puhuu.",
        "listening.a11y.think":   "Mietitään.",
        "listening.header":       "Kuunnellaan...",
        "listening.header.loading": "Ladataan…",

        // Musiikki
        "music.title":         "Muistikuja",
        "music.now_playing":   "Nyt soisee",
        "music.no_songs":      "Kirjastostasi ei löytynyt kappaleita.\nLisää musiikkia Apple Musiciin ja palaa takaisin.",
        "music.connect.title": "Yhdistä Apple Music",
        "music.connect.desc":  "Salli pääsy toistaaksesi suosikkikappaleesi Apple Music -kirjastostasi.",
        "music.connect.btn":   "Yhdistä",
        "music.denied":        "Apple Music -pääsy evättiin.\nOta se käyttöön asetuksissa › Tietosuoja › Media ja Apple Music.",
        "music.loading":       "Ladataan musiikkiasi…",
        "music.mixes":         "Muistosoittolistat",

        // Malliasetukset
        "modelsettings.title":          "Äänitekoälymalli",
        "modelsettings.status":         "Tila",
        "modelsettings.ready":          "Gemma 4 valmis",
        "modelsettings.not_downloaded": "Mallia ei ladattu",
        "modelsettings.model.desc":     "Google Gemma 4 E2B — paras laitteen tekoäly",
        "modelsettings.download":       "Lataa",
        "modelsettings.downloading":    "Ladataan Gemma 4 E2B…",
        "modelsettings.download.cancel": "Peruuta lataus",
        "modelsettings.download.button": "Lataa Gemma 4 E2B",
        "modelsettings.download.done":   "Gemma 4 ladattu ja valmis",
        "modelsettings.download.desc":   "Gemma 4 E2B on Googlen paras laitteen tekoälymalli (~2,3 Gt). Wi-Fi-yhteys suositellaan.",
        "modelsettings.storage":         "Tallennustila",
        "modelsettings.storage.available": "Vapaata tallennustilaa",
        "modelsettings.storage.delete":  "Poista",
        "modelsettings.storage.on_disk": "%.1f Gt levyllä",

        // Äänivalinta
        "voiceselection.title":             "Tekoälyääni",
        "voiceselection.section.companion": "Tekoälykumppanin ääni",
        "voiceselection.default":           "Oletusääni",
        "voiceselection.default.subtitle":  "Apple TTS (englanti)",
        "voiceselection.personal.section":  "iOS Henkilökohtainen ääni",
        "voiceselection.personal.empty":    "Henkilökohtaisia ääniä ei löydy. Luo sellainen iOS-asetuksissa → Esteettömyys → Henkilökohtainen ääni.",
        "voiceselection.personal.enable":   "Ota iOS Henkilökohtainen ääni käyttöön",
        "voiceselection.personal.subtitle": "Applen esteettömyysääni (aseta iPhone-asetuksissa)",
        "voiceselection.footer":            "iOS Henkilökohtainen ääni on Applen oma esteettömyysominaisuus — ei liity äänen kloonaukseen. Aseta se iPhone-asetuksissa → Esteettömyys → Henkilökohtainen ääni (~15 min).",
        "voiceselection.personal.label":    "Henkilökohtainen ääni",
        "voiceselection.personal.denied":   "Henkilökohtainen ääni -pääsy evätty. Ota käyttöön iOS-asetuksissa → Tietosuoja → Henkilökohtainen ääni.",
        "voiceselection.personal.unsupported": "Henkilökohtainen ääni ei ole tuettu tällä laitteella.",

        // Äänitila-asetukset
        "voicemode.active":                 "Aktiivinen tila",
        "voicemode.offline_desc":           "Toimii täysin offline · Tietosi eivät poistu puhelimestasi",
        "voicemode.model.ready":            "Gemma 4 -malli valmis",
        "voicemode.model.ready.desc":       "2,3 Gt · Ladattu",
        "voicemode.model.not_downloaded":   "Gemma 4 -mallia ei ladattu",
        "voicemode.model.download_hint":    "Napauta ladataksesi · 2,3 Gt vaaditaan",
        "voicemode.about":                  "Tietoja",
        "voicemode.privacy.title":          "Yksityisyytesi",
        "voicemode.privacy.text":           "Kaikki keskustelut suoritetaan täysin iPhonellasi. Mitään ääntä, tekstiä tai henkilötietoja ei koskaan lähetetä ulkoisille palvelimille.",
        "voicemode.offline.title":          "Toimii offline-tilassa",
        "voicemode.offline.text":           "Kun Gemma 4 -malli on ladattu, Welcome Back toimii ilman internetyhteyttä.",

        // Ilmoitukset
        "notifications.title":               "Ilmoitukset",
        "notifications.status":              "Tila",
        "notifications.enable":              "Ota ilmoitukset käyttöön",
        "notifications.checkin":             "Päivittäiset muistutukset",
        "notifications.remind_at":           "Muistuta minua klo",
        "notifications.topics.title":        "Mistä puhua",
        "notifications.topics.header":       "Aiheet ja muistutukset",
        "notifications.topics.placeholder":  "Kuvaile, mihin päivittäinen muistutus tulisi keskittyä — esim. lääkitys, tapaamiset, muistot.",

        // Kieliasetukset
        "languagesettings.title":    "Kieli",
        "languagesettings.subtitle": "Valitse sovelluksessa käytettävä kieli.",
    ]
}
